/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proway_swing;

import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author 74703
 */
public class exemlocampus extends javax.swing.JFrame {

    /**
     * Creates new form exemlocampus
     */
    public exemlocampus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtonProcessar = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelSobrenome = new javax.swing.JLabel();
        jTextFieldSobrenome = new javax.swing.JTextField();
        jLabelMesNascimento = new javax.swing.JLabel();
        jComboBoxMesnascimento = new javax.swing.JComboBox<>();
        jLabelAnoNascimento = new javax.swing.JLabel();
        jSpinnerAnoNascimento = new javax.swing.JSpinner();
        jLabelAreaDeAtuacao = new javax.swing.JLabel();
        jCheckBoxBackEnd = new javax.swing.JCheckBox();
        jCheckBoxFrontEnd = new javax.swing.JCheckBox();
        jLabelSexo = new javax.swing.JLabel();
        jRadioButtonSexo = new javax.swing.JRadioButton();
        jLabelDescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jButtonCancelar = new javax.swing.JButton();
        jRadioButtonSexo2 = new javax.swing.JRadioButton();
        jCheckBoxTermosDeUso = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jButtonExport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonProcessar.setText("processar");
        jButtonProcessar.setEnabled(false);
        jButtonProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcessarActionPerformed(evt);
            }
        });

        jLabelNome.setText("Nome");

        jLabelSobrenome.setText("Sobrenome");

        jLabelMesNascimento.setText("Mês nascimento");

        jComboBoxMesnascimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novemro", "Dezembro" }));
        jComboBoxMesnascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMesnascimentoActionPerformed(evt);
            }
        });

        jLabelAnoNascimento.setText("Ano nascimento");

        jSpinnerAnoNascimento.setValue(2024);

        jLabelAreaDeAtuacao.setText("Área de atuação");

        jCheckBoxBackEnd.setText("Back-End");

        jCheckBoxFrontEnd.setText("Front-End");

        jLabelSexo.setText("sexo");

        buttonGroup1.add(jRadioButtonSexo);
        jRadioButtonSexo.setText("Masculino");

        jLabelDescricao.setText("Descrição");

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricao);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonSexo2);
        jRadioButtonSexo2.setText("Feminino");

        jCheckBoxTermosDeUso.setText("Eu concordo com os termos de acordo");
        jCheckBoxTermosDeUso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxTermosDeUsoItemStateChanged(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sobrenome", "Mês nascimento", "Ano nascimento", "Área de atuação", "Sexo", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonApagar.setText("Apagar");

        jButtonExport.setText("Export");
        jButtonExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSobrenome)
                    .addComponent(jCheckBoxTermosDeUso)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonProcessar))
                    .addComponent(jLabelDescricao)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabelAreaDeAtuacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                        .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldSobrenome, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jComboBoxMesnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMesNascimento)))
                            .addComponent(jCheckBoxBackEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxFrontEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAnoNascimento)
                            .addComponent(jSpinnerAnoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonSexo2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonExport, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonApagar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelSobrenome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMesNascimento)
                            .addComponent(jLabelAnoNascimento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxMesnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerAnoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAreaDeAtuacao)
                            .addComponent(jLabelSexo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonSexo)
                            .addComponent(jCheckBoxBackEnd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxFrontEnd)
                            .addComponent(jRadioButtonSexo2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxTermosDeUso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCancelar)
                            .addComponent(jButtonProcessar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEditar)
                            .addComponent(jButtonApagar)
                            .addComponent(jButtonExport))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcessarActionPerformed
        // get == obter algo
        // set == definir algo

        //obter o nome que o usuario digitou do campo de texto (jtextField1)
        String nome = jTextFieldNome.getText();
        //obter o sobrenome que o usuario digitou do campo de texto (jtextField2)
        String sobrenome = jTextFieldSobrenome.getText();

        String mesNascimento = (String) jComboBoxMesnascimento.getSelectedItem();
        int anoNascimento = Integer.parseInt(jSpinnerAnoNascimento.getValue().toString());
        String sexo = "";
        if (jRadioButtonSexo2.isSelected() == true) {
            sexo = "Feminino";
        } else if (jRadioButtonSexo.isSelected() == true) {
            sexo = "Masculino";
        }
        boolean ehBackEnd = jCheckBoxBackEnd.isSelected();
        boolean ehFrontEnd = jCheckBoxFrontEnd.isSelected();
        String descricao = jTextAreaDescricao.getText();
        String nomecompleto = nome + " " + sobrenome;

        String areaAtuacao = "Full Stack";
        if (ehBackEnd == true && ehFrontEnd == false) {
            areaAtuacao = "Back-End";
        } else if (ehBackEnd == false && ehFrontEnd == true) {
            areaAtuacao = "Front-End";
        }

        var modeloTabela = (DefaultTableModel) jTable1.getModel();

        modeloTabela.addRow(new Object[]{
            nome,
            sobrenome,
            mesNascimento,
            anoNascimento,
            areaAtuacao,
            sexo,
            descricao
        });
        salvarNoExcel();

        JOptionPane.showConfirmDialog(null, "Cadastrado com sucesso");


    }//GEN-LAST:event_jButtonProcessarActionPerformed
    private void salvarNoExcel() {
        var modelo = (DefaultTableModel) jTable1.getModel();

        try ( Workbook excel = new XSSFWorkbook()) {
            Sheet planilha = excel.createSheet("Colaboradores");

            Row linhaCabecalho = planilha.createRow(0);
            linhaCabecalho.createCell(0).setCellValue("Nome");
            linhaCabecalho.createCell(1).setCellValue("Sobrenome");
            linhaCabecalho.createCell(2).setCellValue("Mês Nascimento");
            linhaCabecalho.createCell(3).setCellValue("Ano Nascimento");
            linhaCabecalho.createCell(4).setCellValue("Área de Atuação");
            linhaCabecalho.createCell(5).setCellValue("Sexo");
            linhaCabecalho.createCell(6).setCellValue("Descrição");
            // Pegar o modelo da tabela

            // Percorrer cada uma das linhas da tabela
            for (var i = 0; i < modelo.getRowCount(); i++) {
                // Obter o nome do produto da linha iterada
                String nome = modelo.getValueAt(i, 0).toString();
                String sobrenome = modelo.getValueAt(i, 1).toString();
                String mesNascimento = modelo.getValueAt(i, 2).toString();
                String anoNascimento = modelo.getValueAt(i, 3).toString();
                String areaAtuacao = modelo.getValueAt(i, 4).toString();
                String sexo = modelo.getValueAt(i, 5).toString();
                String descricao = modelo.getValueAt(i, 6).toString();
                // Criar uma linha na planilha
                Row linha = planilha.createRow(i + 1);
                // Criar uma célula definindo o nome do produto da linha iterada
                linha.createCell(0).setCellValue(nome);
                linha.createCell(1).setCellValue(sobrenome);
                linha.createCell(2).setCellValue(mesNascimento);
                linha.createCell(3).setCellValue(anoNascimento);
                linha.createCell(4).setCellValue(areaAtuacao);
                linha.createCell(5).setCellValue(sexo);
                linha.createCell(6).setCellValue(descricao);
            }

            // Obter o caminho da pasta da área de trabalho do usuário
            var caminhoDesktop = Paths.get(
                    System.getProperty("user.home"), "Desktop");
            // Obter o caminho do arquivo do excel que será importado
            var caminhoArquivo = caminhoDesktop.resolve("example.xlsx");

            FileOutputStream arquivoSaida = new FileOutputStream(caminhoArquivo.toFile());
            excel.write(arquivoSaida);
            arquivoSaida.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private String getTextoBoolean(Boolean Value) {
        if (Value == true) {
            return "Sim";
        } else {
            return "Nâo";
        }
    }

    private void jComboBoxMesnascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMesnascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMesnascimentoActionPerformed

    private void jCheckBoxTermosDeUsoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxTermosDeUsoItemStateChanged
        boolean termosDeAcordoAceitos = jCheckBoxTermosDeUso.isSelected();

        if (termosDeAcordoAceitos == true) {
            jButtonProcessar.setEnabled(true);
            jButtonCancelar.setEnabled(true);
        } else {
            jButtonProcessar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxTermosDeUsoItemStateChanged

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldNome.setText("");
        jTextFieldSobrenome.setText("");
        jTextAreaDescricao.setText("");

        jCheckBoxBackEnd.setSelected(false);
        jCheckBoxFrontEnd.setSelected(false);
        jCheckBoxTermosDeUso.setSelected(false);

        buttonGroup1.clearSelection();

        jSpinnerAnoNascimento.setValue(2024);

        jComboBoxMesnascimento.setSelectedIndex(0);


    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportActionPerformed
        try ( Workbook planilha = new XSSFWorkbook()) {
            Sheet folha = planilha.createSheet("Produtos");

            Row linhaCabecalho = folha.createRow(0);
            linhaCabecalho.createCell(0).setCellValue("Nome");

            Row linhaPrimeiroRegistro = folha.createRow(1);
            linhaPrimeiroRegistro.createCell(0).setCellValue("Maçã");

            Path caminhoDesktop = Paths.get(
                    System.getProperty("user.home"), "Desktop");
            Path caminhoArquivo = caminhoDesktop.resolve("example.xlsx");

            FileOutputStream arquivoSaida = new FileOutputStream(caminhoArquivo.toFile());
            planilha.write(arquivoSaida);
            arquivoSaida.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonExportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exemlocampus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exemlocampus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exemlocampus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exemlocampus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exemlocampus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExport;
    private javax.swing.JButton jButtonProcessar;
    private javax.swing.JCheckBox jCheckBoxBackEnd;
    private javax.swing.JCheckBox jCheckBoxFrontEnd;
    private javax.swing.JCheckBox jCheckBoxTermosDeUso;
    private javax.swing.JComboBox<String> jComboBoxMesnascimento;
    private javax.swing.JLabel jLabelAnoNascimento;
    private javax.swing.JLabel jLabelAreaDeAtuacao;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelMesNascimento;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelSobrenome;
    private javax.swing.JRadioButton jRadioButtonSexo;
    private javax.swing.JRadioButton jRadioButtonSexo2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerAnoNascimento;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldSobrenome;
    // End of variables declaration//GEN-END:variables
}
