/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proway_swing.telas;

import com.mycompany.proway_swing.bancoDados.Banco;
import com.mycompany.proway_swing.entidades.Categoria;
import com.mycompany.proway_swing.entidades.Filme;
import com.mycompany.proway_swing.repositorios.CategoriaRepositorio;
import com.mycompany.proway_swing.repositorios.FilmeRepositorio;
import javax.swing.JOptionPane;
import java.sql.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class FilmeJFrame extends javax.swing.JFrame {

    private int idEscolhido = -1;

    /**
     * Creates new form FilmeJFrame
     */
    public FilmeJFrame() {
        initComponents();
        listarFilmes();
        popularComboBoxCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLista = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFilmes = new javax.swing.JTable();
        jButtonEditarLista = new javax.swing.JButton();
        jButtonApagarLista = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jButtomCadastrarNome = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelCategoria = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jFormattedTextFieldorcamento = new javax.swing.JFormattedTextField();
        jFormattedTextFieldbilheteria = new javax.swing.JFormattedTextField();
        jSliderclassificacao = new javax.swing.JSlider();
        jFormattedTextFielddatadepublicacao = new javax.swing.JFormattedTextField();
        jFormattedTextFieldduracao = new javax.swing.JFormattedTextField();
        jLabelorcamento = new javax.swing.JLabel();
        jLabeldiretor = new javax.swing.JLabel();
        jLabeldatadepublicacao = new javax.swing.JLabel();
        jLabelbilheteria = new javax.swing.JLabel();
        jLabelclassificacao = new javax.swing.JLabel();
        jLabelduracao = new javax.swing.JLabel();
        jTextFielddiretor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelLista.setText("Lista de Filmes");

        jTableFilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Categorias", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableFilmes);
        if (jTableFilmes.getColumnModel().getColumnCount() > 0) {
            jTableFilmes.getColumnModel().getColumn(1).setResizable(false);
            jTableFilmes.getColumnModel().getColumn(2).setResizable(false);
        }

        jButtonEditarLista.setText("Editar");
        jButtonEditarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarListaActionPerformed(evt);
            }
        });

        jButtonApagarLista.setText("Apagar");
        jButtonApagarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarListaActionPerformed(evt);
            }
        });

        jLabelNome.setText("Nome");

        jButtomCadastrarNome.setText("Cadastrar");
        jButtomCadastrarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtomCadastrarNomeActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelCategoria.setText("Categoria");

        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });

        jFormattedTextFieldbilheteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldbilheteriaActionPerformed(evt);
            }
        });

        jSliderclassificacao.setMinorTickSpacing(5);
        jSliderclassificacao.setPaintTicks(true);

        jFormattedTextFielddatadepublicacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jFormattedTextFieldduracao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        jLabelorcamento.setText("orçamento");

        jLabeldiretor.setText("Diretor");

        jLabeldatadepublicacao.setText("Data de publicação");

        jLabelbilheteria.setText("Bilheteria");

        jLabelclassificacao.setText("Classificação");

        jLabelduracao.setText("Duração");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelLista)
                        .addGap(205, 205, 205)
                        .addComponent(jButtonEditarLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonApagarLista)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jFormattedTextFielddatadepublicacao, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                                .addComponent(jTextFieldNome)
                                .addComponent(jFormattedTextFieldorcamento)
                                .addComponent(jTextFielddiretor, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNome)
                                .addComponent(jLabelorcamento)
                                .addComponent(jLabeldatadepublicacao))
                            .addComponent(jLabeldiretor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelbilheteria))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBoxCategoria, 0, 250, Short.MAX_VALUE)
                                .addComponent(jLabelCategoria)
                                .addComponent(jFormattedTextFieldbilheteria)
                                .addComponent(jSliderclassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFormattedTextFieldduracao))
                            .addComponent(jLabelclassificacao)
                            .addComponent(jLabelduracao)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtomCadastrarNome)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLista)
                    .addComponent(jButtonEditarLista)
                    .addComponent(jButtonApagarLista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelorcamento)
                    .addComponent(jLabelbilheteria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldbilheteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldorcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabeldiretor)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSliderclassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFielddiretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelclassificacao))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeldatadepublicacao)
                    .addComponent(jLabelduracao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFielddatadepublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldduracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtomCadastrarNome))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtomCadastrarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtomCadastrarNomeActionPerformed

        var nome = jTextFieldNome.getText();
        var categoria = (Categoria) jComboBoxCategoria.getSelectedItem();
        var bilheteria = Double.parseDouble(jFormattedTextFieldbilheteria.getText());
        var orcamento = Double.parseDouble(jFormattedTextFieldorcamento.getText());
        var diretor = jTextFielddiretor.getText().trim();
        var classificacao = jSliderclassificacao.getValue();
        // dd/mm/yyyy
        var dataPublicacao = LocalDate.parse(
         jFormattedTextFielddatadepublicacao.getText(),
                DateTimeFormatter.ofPattern("dd/MM/yyyy")
        );
        // hh:mm
        var duracao = LocalTime.parse(
                jFormattedTextFieldduracao.getText(),
                DateTimeFormatter.ISO_LOCAL_TIME
        );
                
        
        

        // instanciando um objeto da classe filme
        var filme = new Filme();
        // preenchendo as propriedades do objeto filme com os dados que
        // o usuário preencheu
        filme.setNome(nome);
        filme.setCategoria(categoria);
        filme.setBilheteria(bilheteria);
        filme.setOrcamento(orcamento);
        filme.setDiretor(diretor);
        filme.setClassificacao((byte)classificacao);
        filme.setDuracao(duracao);
        filme.setDataPublicacao(dataPublicacao);
        // instanciando um objeto da classe FilmeRepositorio, para realisar
        // o insert na tabela de filmes
        var filmeRepositorio = new FilmeRepositorio();
        if (idEscolhido == -1) {
            //chamando o método inserir passando o objeto filme como parâmetro
            filmeRepositorio.inserir(filme);
        } else {
            filme.setId(  idEscolhido);
            filmeRepositorio.alterar(filme);
            idEscolhido = -1; // Retornar para o modo de cadatro
        }

        listarFilmes();

        JOptionPane.showMessageDialog(null, "Filme cadastrado com sucesso");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtomCadastrarNomeActionPerformed

    private void jButtonApagarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarListaActionPerformed
        int indiceLinhaSelecionada = jTableFilmes.getSelectedRow(); // TODO add your handling code here:
        var idEscolhidoParaApagar = Integer.parseInt(jTableFilmes
                .getValueAt(indiceLinhaSelecionada, 0).toString());

        var filmeRepositorio = new FilmeRepositorio();
        filmeRepositorio.apagar(idEscolhidoParaApagar);

        listarFilmes();
        JOptionPane.showMessageDialog(null, ("Filme apagado com sucesso"));
    }//GEN-LAST:event_jButtonApagarListaActionPerformed

    private void jButtonEditarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarListaActionPerformed
        var indiceLinhaSelecionada = jTableFilmes.getSelectedRow();
        idEscolhido = Integer.parseInt(jTableFilmes
                .getValueAt(indiceLinhaSelecionada, 0).toString());
        var filmeRepositorio = new FilmeRepositorio();
        var filme = filmeRepositorio.obterPorId(idEscolhido);
        jTextFieldNome.setText(filme.getNome());
        for (int i = 0; i < jComboBoxCategoria.getItemCount(); i++) {
            var item = (Categoria) jComboBoxCategoria.getItemAt(i);
            if (item.getId() == filme.getCategoria().getId()) {
                jComboBoxCategoria.setSelectedItem(item);
            }
        }

        /**
         * Exercício: Criar uma tabela chamada categorias com as seguintes
         * colunas id: gerada automáticamente, chave primária nome: texto
         * obrigatório Criar um sistema (CRUD) assim como o FilmeJFFrame
         */
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarListaActionPerformed

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    private void jFormattedTextFieldbilheteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldbilheteriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldbilheteriaActionPerformed

    private void listarFilmes() {
        var modeloTabela = (DefaultTableModel) jTableFilmes.getModel();
        // remover todos os elementos do jTable
        modeloTabela.setRowCount(0);
        var filmeRepositorio = new FilmeRepositorio();
        var filmes = filmeRepositorio.obterTodos();
        for (int i = 0; i < filmes.size(); i++) {
            var filme = filmes.get(i);
            modeloTabela.addRow(new Object[]{
                filme.getId(),
                filme.getCategoria().getNome(),
                filme.getNome()
            });
        }

    }

    private void popularComboBoxCategorias() {
        var categoriaRepositorio = new CategoriaRepositorio();
        var categorias = categoriaRepositorio.obterTodos();

        for (int i = 0; i < categorias.size(); i++) {
            var categoria = categorias.get(i);
            jComboBoxCategoria.addItem(categoria);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilmeJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilmeJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilmeJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilmeJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilmeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtomCadastrarNome;
    private javax.swing.JButton jButtonApagarLista;
    private javax.swing.JButton jButtonEditarLista;
    private javax.swing.JComboBox<Categoria> jComboBoxCategoria;
    private javax.swing.JFormattedTextField jFormattedTextFieldbilheteria;
    private javax.swing.JFormattedTextField jFormattedTextFielddatadepublicacao;
    private javax.swing.JFormattedTextField jFormattedTextFieldduracao;
    private javax.swing.JFormattedTextField jFormattedTextFieldorcamento;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelLista;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelbilheteria;
    private javax.swing.JLabel jLabelclassificacao;
    private javax.swing.JLabel jLabeldatadepublicacao;
    private javax.swing.JLabel jLabeldiretor;
    private javax.swing.JLabel jLabelduracao;
    private javax.swing.JLabel jLabelorcamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSliderclassificacao;
    private javax.swing.JTable jTableFilmes;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFielddiretor;
    // End of variables declaration//GEN-END:variables
}
